Update to Edit Card Packages
CSC207-2022F-UofT/course-project-team-flash pull request #35
Opened 2022-11-19 00:09 UTC by AlbertYS

Changes to EditCardInputData such that it uses card id number rather than card itself, now accepts editing of options with overloaded constructors EditCardInputBoundary changes as required

Updated implementations for:
EditCardInteractor
EditCardInputBoundary
EditCardController

2022-11-20 21:20 UTC, derrickcho3715 submitted a review, later dismissed
This looks good. All the proper documentation is there and it has all the necessary files including tests. One thing to note is that the EditCardInteractor is missing a call to EditCardOutputBoundary. Apart from that it's good work.

2022-11-20 21:51 UTC, jakan9 approved these changes

2022-11-20 21:55 UTC, jakan9 approved these changes

2022-11-20 22:15 UTC, aldob02 requested changes

2022-11-20 22:15 UTC, aldob02 commented on src/main/java/editCard/EditCardInteractor.java
> -public class EditCardInteractor {
The interactor needs to implement the input boundary.

2022-11-20 22:19 UTC, aldob02 approved these changes
Looks good, only testing and javadocs are needed.

2022-11-21 00:02 UTC, derrickcho3715 approved these changes
This looks good. All the proper documentation is there and it has all the necessary files including tests. The issue with the interactor and output boundary was properly addressed.

2022-11-21 00:19 UTC, merged